"Спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Маппинг":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/*.yml'
    - 'Resources/Prototypes/Maps/*.yml'

"Прототипы":
- changed-files:
  - any-glob-to-any-file: '**/*.yml*'

"UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"No C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"
