- type: job
  id: JediNt
  name: страж клинка
  description: Встань на защиту станции со своим крутым мечом и способностями!
  playTimeTracker: JobJediNt
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000
  startingGear: JediNtGear
  icon: "JobIconJediNt"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: JediNtGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJediNt
    back: ClothingBackpackJediNtFilled
    shoes: ClothingShoesBootsJackJediNt
    eyes: ClothingEyesGlassesSunglasses
    # head: ClothingHeadHatBeretSP
    outerClothing: ClothingOuterVestJediNt
    id: JediNtPDA
    ears: ClothingHeadsetJediNtAlt
    belt: ClothingBeltSecurityFilled
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckCloakJediNt
  # innerclothingskirt: ClothingUniformJumpskirtSP
  # satchel: ClothingBackpackSatchelSpacePrisonFilled
  # duffelbag: ClothingBackpackDuffelSpacePrisonFilled
